### ISSUE TITLE
Add CC_TEST_REPORTER_ID to Github repository secret

### ISSUE THREAD

**Issue by cyri113** [RnDAO/tc-dbComm#56]
In order to report the test results to CodeClimate, we need to provide a key `CC_TEST_REPORTER_ID`.

## Task

- [ ] Go to https://codeclimate.com/github/RnDAO/tc-dbComm
- [ ] Go to the **Repo Settings**
- [ ] Go to **Test coverage**
- [ ] Copy the `TEST REPORTER ID`
- [ ] Go to https://github.com/RnDAO/tc-dbComm/settings/secrets/actions
- [ ] Click on **New repository secret**
- [ ] Enter the name (`CC_TEST_REPORTER_ID`) and paste the TEST REPORTER ID in the Secret.
- [ ] Click on **Add secret**
